tests :
      - ("tests/tests-images/google/weat3.jsonl", "data/google-images/weat3")
      - ("tests/tests-images/google/sent-weat3.jsonl", "data/google-images/weat3")
      - ("tests/tests-images/google/weat6.jsonl", "data/google-images/weat6")
      - ("tests/tests-images/google/sent-weat6.jsonl", "data/google-images/weat6")
      - ("tests/tests-images/google/weat8.jsonl", "data/google-images/weat8")
      - ("tests/tests-images/google/sent-weat8.jsonl", "data/google-images/weat8")
      - ("tests/tests-images/google/weat11.jsonl", "data/google-images/weat11")
      - ("tests/tests-images/google/sent-weat11.jsonl", "data/google-images/weat11")
      - ("tests/tests-images/google/weat12.jsonl", "data/google-images/weat12")
      - ("tests/tests-images/google/sent-weat12.jsonl", "data/google-images/weat12")
      - ("tests/tests-images/google/weat13.jsonl", "data/google-images/weat13")
      - ("tests/tests-images/google/sent-weat13.jsonl", "data/google-images/weat13")
      - ("tests/tests-images/google/heilman_MF_double_bind_competent_one_sentence.jsonl", "data/google-images/heilman-MF-double-bind-competent-one-sent")
      - ("tests/tests-images/google/heilman_MF_double_bind_likable_one_sentence.jsonl", "data/google-images/he ilman-MF-double-bind-competent-one-word")
      - ("tests/tests-images/google/heilman_MF_double_bind_competent_one_word.jsonl", "data/google-images/heilman-MF-double-bind-likable-one-sent")
      - ("tests/tests-images/google/heilman_MF_double_bind_likable_one_word.jsonl", "data/google-images/heilman-MF-double-bind-likable-one-word")
      - ("tests/tests-images/google/heilman_race_double_bind_competent_one_word.jsonl", "data/google-images/heilman-race-double-bind-competent-one-sent")
      - ("tests/tests-images/google/heilman_race_double_bind_competent_one_sentence.jsonl", "data/google-images/heilman-race-double-bind-competent-one-word")
      - ("tests/tests-images/google/heilman_race_double_bind_likable_one_word.jsonl", "data/google-images/heilman-race-double-bind-likable-one-sent")
      - ("tests/tests-images/google/heilman_race_double_bind_likable_one_sentence.jsonl", "data/google-images/heilman-race-double-bind-likable-one-word")
      - ("tests/tests-images/google/occ_MF.jsonl", "data/google-images/occupations-gender")
      - ("tests/tests-images/google/sent-occ_MF.jsonl", "data/google-images/occupations-gender")
      - ("tests/tests-images/google/angry_black_woman_stereotype.jsonl", "data/google-images/angry-black-women")
      - ("tests/tests-images/google/sent-angry_black_woman_stereotype.jsonl", "data/google-images/angry-black-women")
      - ("tests/tests-images/google/occ_race.jsonl", "data/google-images/occupations-race")
      - ("tests/tests-images/google/sent-occ_race.jsonl", "data/google-images/occupations-race")
      - ("tests/tests-images/concap/occ_MF.jsonl", "data/conceptual-captions/images/bias-val")
      - ("tests/tests-images/concap/sent-occ_MF.jsonl", "data/conceptual-captions/images/bias-val")
      - ("tests/tests-images/concap/weat6.jsonl", "data/conceptual-captions/images/bias-val")
      - ("tests/tests-images/concap/sent-weat6.jsonl", "data/conceptual-captions/images/bias-val")
      - ("tests/tests-images/coco/occ_MF.jsonl", "data/COCO/images/bias-val")
      - ("tests/tests-images/coco/sent-occ_MF.jsonl", "data/COCO/images/bias-val")
      - ("tests/tests-images/coco/weat6.jsonl", "data/COCO/images/bias-val")
      - ("tests/tests-images/coco/sent-weat6.jsonl", "data/COCO/images/bias-val")
      - ("tests/tests-images/coco/weat8.jsonl", "data/COCO/images/bias-val")
      - ("tests/tests-images/coco/sent-weat8.jsonl", "data/COCO/images/bias-val")
