log_dir : logs
num_workers : 4
val_workers : 2
batch_size : 256
num_samples: 100000
path_to_obj_list : bottom-up-attention/data/genome/1600-400-20/objects_vocab.txt

test2features : tests/test2features.json
model_type : lxmert
model_archive : pretrained-models/lxmert/pretrained-bert/

tests :
      - tests/grounded-tests/coco/occ_gender.jsonl
      - tests/grounded-tests/coco/sent-occ_gender.jsonl
      - tests/grounded-tests/coco/weat6.jsonl
      - tests/grounded-tests/coco/sent-weat6.jsonl
      - tests/grounded-tests/coco/weat8.jsonl
      - tests/grounded-tests/coco/sent-weat8.jsonl
