log_dir : logs
num_gpus : 1
num_workers : 4
val_workers : 2
batch_size : 64

num_samples : 100000

dataset : coco
model_type : vilbert
model_archive : vilbert_beta/pretrained-models/concap/six_layers_concap
model_config : vilbert_beta/config/bert_base_6layer_6conect.json

bert_model : bert-base-uncased
do_lower_case : True
max_seq_length : 36

task_cfg : vilbert_beta/bias_tasks_coco.yml
fpath_stopwords : scripts/stopwords.txt

# model-specific params
tests : [tests/tests-images/coco/occ_MF.jsonl, tests/tests-images/coco/sent-occ_MF.jsonl, tests/tests-images/coco/weat6.jsonl, tests/tests-images/coco/sent-weat6.jsonl, tests/tests-images/coco/weat8.jsonl, tests/tests-images/coco/sent-weat8.jsonl]
features: [/storage/ccross/bias-grounded-bert/vilbert_beta/features/coco/coco_trainval_resnet101_faster_rcnn_genome.lmdb', /storage/ccross/bias-grounded-bert/vilbert_beta/features/coco/coco_trainval_resnet101_faster_rcnn_genome.lmdb', /storage/ccross/bias-grounded-bert/vilbert_beta/features/coco/coco_trainval_resnet101_faster_rcnn_genome.lmdb', /storage/ccross/bias-grounded-bert/vilbert_beta/features/coco/coco_trainval_resnet101_faster_rcnn_genome.lmdb' /storage/ccross/bias-grounded-bert/vilbert_beta/features/coco/coco_trainval_resnet101_faster_rcnn_genome.lmdb, /storage/ccross/bias-grounded-bert/vilbert_beta/features/coco/coco_trainval_resnet101_faster_rcnn_genome.lmdb]