log_dir : logs
num_gpus : 1
num_workers : 4
val_workers : 2

use_concap : True
model_type : vilbert
model_archive : vilbert_beta/pretrained/six_layers_concap
model_config : vilbert_beta/config/bert_base_6layer_6conect.json

bert_model : bert-base-uncased
do_lower_case : True
max_seq_length : 36

# model-specific params
num_workers : 3
batch_size : 64

num_samples : 100000

fpaths_tests : [
      #tests/tests-images/google/weat3.jsonl,
      tests/tests-images/google/sent-weat3.jsonl,
      tests/tests-images/google/weat6.jsonl,
      tests/tests-images/google/sent-weat6.jsonl,
      tests/tests-images/google/weat8.jsonl,
      tests/tests-images/google/sent-weat8.jsonl,
      tests/tests-images/google/weat11.jsonl,
      tests/tests-images/google/sent-weat11.jsonl,
      tests/tests-images/google/weat12.jsonl,
      tests/tests-images/google/sent-weat12.jsonl,
      tests/tests-images/google/heilman_MF_double_bind_competent_one_sentence.jsonl,
      tests/tests-images/google/heilman_MF_double_bind_likable_one_sentence.jsonl,
      tests/tests-images/google/heilman_MF_double_bind_competent_one_word.jsonl,
      tests/tests-images/google/heilman_MF_double_bind_likable_one_word.jsonl,
      tests/tests-images/google/occ.jsonl
   ]
