log_dir : logs
num_gpus : 1
num_workers : 4
val_workers : 2

use_concap : True
model_type : vilbert
model_archive : vilbert_beta/pretrained/six_layers_concap
model_config : vilbert_beta/config/bert_base_6layer_6conect.json

bert_model : bert-base-uncased
do_lower_case : True
max_seq_length : 36

# model-specific params
num_workers : 3
tests : tests/tests-images
batch_size : 64

num_samples : 100000