log_dir : logs
num_gpus : 1
num_workers : 4
val_workers : 2

fpath_stopwords : scripts/stopwords.txt

model_type : vilbert
model_archive : vilbert_beta/pretrained-models/concap/six_layers_concap
model_config : vilbert_beta/config/bert_base_6layer_6conect.json

bert_model : bert-base-uncased
do_lower_case : True
max_seq_length : 36

dataset : concap
task_cfg : vilbert_beta/bias_tasks_google.yml

# model-specific params
num_workers : 3
batch_size : 64

num_samples : 100000
tests : [
     #tests/tests-images/concap/occ_MF.jsonl,
     tests/tests-images/concap/sent-occ_MF.jsonl,
     #tests/tests-images/concap/weat6.jsonl,
     #tests/tests-images/concap/sent-weat6.jsonl
     ]
features: [
#/storage/ccross/bias-grounded-bert/vilbert_beta/features/conceptual/conceptual_resnet101_faster_rcnn_genome.lmdb,
/storage/ccross/bias-grounded-bert/vilbert_beta/features/conceptual/conceptual_resnet101_faster_rcnn_genome.lmdb,
#/storage/ccross/bias-grounded-bert/vilbert_beta/features/conceptual/conceptual_resnet101_faster_rcnn_genome.lmdb,
#/storage/ccross/bias-grounded-bert/vilbert_beta/features/conceptual/conceptual_resnet101_faster_rcnn_genome.lmdb
]