log_dir : logs
num_gpus : 1
num_workers : 4
val_workers : 2

fpath_stopwords : scripts/stopwords.txt

use_concap : True
model_type : vilbert
model_archive : vilbert_beta/pretrained-models/concap/six_layers_concap
model_config : vilbert_beta/config/bert_base_6layer_6conect.json

bert_model : bert-base-uncased
do_lower_case : True
max_seq_length : 36

dataset : custom
task_cfg : vilbert_beta/bias_tasks_google.yml 

# model-specific params
num_workers : 3
batch_size : 64

num_samples : 100000
tests : [
     tests/tests-images/google/weat3.jsonl,
     tests/tests-images/google/sent-weat3.jsonl,
     tests/tests-images/google/weat6.jsonl,
     tests/tests-images/google/sent-weat6.jsonl,
     tests/tests-images/google/weat8.jsonl,
     tests/tests-images/google/sent-weat8.jsonl,
     tests/tests-images/google/weat11.jsonl,
     tests/tests-images/google/sent-weat11.jsonl,
     tests/tests-images/google/weat12.jsonl,
     tests/tests-images/google/sent-weat12.jsonl,
     tests/tests-images/google/weat13.jsonl,
     tests/tests-images/google/sent-weat13.jsonl,
     tests/tests-images/google/heilman_MF_double_bind_competent_one_word.jsonl,
     tests/tests-images/google/heilman_MF_double_bind_competent_one_sentence.jsonl,
     tests/tests-images/google/heilman_MF_double_bind_likable_one_word.jsonl,
     tests/tests-images/google/heilman_MF_double_bind_likable_one_sentence.jsonl,
     tests/tests-images/google/heilman_race_double_bind_competent_one_word.jsonl,
     tests/tests-images/google/heilman_race_double_bind_competent_one_sentence.jsonl,
     tests/tests-images/google/heilman_race_double_bind_likable_one_word.jsonl,
     tests/tests-images/google/heilman_race_double_bind_likable_one_sentence.jsonl,
     tests/tests-images/google/angry_black_woman_stereotype.jsonl,
     tests/tests-images/google/sent-angry_black_woman_stereotype.jsonl,
     tests/tests-images/google/occ_MF.jsonl,
     tests/tests-images/google/sent-occ_MF.jsonl,
     tests/tests-images/google/occ_race.jsonl,
     tests/tests-images/google/sent-occ_race.jsonl
     ]
features: [
          '/storage/ccross/bias-grounded-bert/vilbert_beta/features/google-images/weat3_resnet101_faster_rcnn_genome.lmdb',
          '/storage/ccross/bias-grounded-bert/vilbert_beta/features/google-images/weat3_resnet101_faster_rcnn_genome.lmdb',
          '/storage/ccross/bias-grounded-bert/vilbert_beta/features/google-images/weat6_resnet101_faster_rcnn_genome.lmdb',
          '/storage/ccross/bias-grounded-bert/vilbert_beta/features/google-images/weat6_resnet101_faster_rcnn_genome.lmdb',
          '/storage/ccross/bias-grounded-bert/vilbert_beta/features/google-images/weat8_resnet101_faster_rcnn_genome.lmdb',
          '/storage/ccross/bias-grounded-bert/vilbert_beta/features/google-images/weat8_resnet101_faster_rcnn_genome.lmdb',
          '/storage/ccross/bias-grounded-bert/vilbert_beta/features/google-images/weat11_resnet101_faster_rcnn_genome.lmdb',
          '/storage/ccross/bias-grounded-bert/vilbert_beta/features/google-images/weat11_resnet101_faster_rcnn_genome.lmdb',
          '/storage/ccross/bias-grounded-bert/vilbert_beta/features/google-images/weat12_resnet101_faster_rcnn_genome.lmdb',
          '/storage/ccross/bias-grounded-bert/vilbert_beta/features/google-images/weat12_resnet101_faster_rcnn_genome.lmdb',
          '/storage/ccross/bias-grounded-bert/vilbert_beta/features/google-images/weat13_resnet101_faster_rcnn_genome.lmdb',
          '/storage/ccross/bias-grounded-bert/vilbert_beta/features/google-images/weat13_resnet101_faster_rcnn_genome.lmdb',
          '/storage/ccross/bias-grounded-bert/vilbert_beta/features/google-images/heilman_MF_competent_word_resnet101_faster_rcnn_genome.lmdb',
          '/storage/ccross/bias-grounded-bert/vilbert_beta/features/google-images/heilman_MF_competent_sent_resnet101_faster_rcnn_genome.lmdb',
          '/storage/ccross/bias-grounded-bert/vilbert_beta/features/google-images/heilman_MF_likable_word_resnet101_faster_rcnn_genome.lmdb',
          '/storage/ccross/bias-grounded-bert/vilbert_beta/features/google-images/heilman_MF_likable_sent_resnet101_faster_rcnn_genome.lmdb',
          '/storage/ccross/bias-grounded-bert/vilbert_beta/features/google-images/heilman_race_competent_word_resnet101_faster_rcnn_genome.lmdb',
          '/storage/ccross/bias-grounded-bert/vilbert_beta/features/google-images/heilman_race_competent_sent_resnet101_faster_rcnn_genome.lmdb',
          '/storage/ccross/bias-grounded-bert/vilbert_beta/features/google-images/heilman_race_likable_word_resnet101_faster_rcnn_genome.lmdb',
          '/storage/ccross/bias-grounded-bert/vilbert_beta/features/google-images/heilman_race_likable_sent_resnet101_faster_rcnn_genome.lmdb',
          '/storage/ccross/bias-grounded-bert/vilbert_beta/features/google-images/angry_black_resnet101_faster_rcnn_genome.lmdb',
          '/storage/ccross/bias-grounded-bert/vilbert_beta/features/google-images/angry_black_resnet101_faster_rcnn_genome.lmdb',
          '/storage/ccross/bias-grounded-bert/vilbert_beta/features/google-images/occ_MF_resnet101_faster_rcnn_genome.lmdb',
          '/storage/ccross/bias-grounded-bert/vilbert_beta/features/google-images/occ_MF_resnet101_faster_rcnn_genome.lmdb',
          '/storage/ccross/bias-grounded-bert/vilbert_beta/features/google-images/occ_race_resnet101_faster_rcnn_genome.lmdb',
          '/storage/ccross/bias-grounded-bert/vilbert_beta/features/google-images/occ_race_resnet101_faster_rcnn_genome.lmdb'
          ]