log_dir : logs
num_workers : 4
val_workers : 2

model_type : vilbert
max_seq_length : 36
dataset_type: concap

test2features : tests/test2features.json
path_to_obj_list : image-features/vilbert_objects_vocab.txt

model_type : vilbert
model_archive : pretrained-models/vilbert/six_layers_concap
model_config : pretrained-models/vilbert/bert_base_6layer_6conect.json

# model-specific params
num_workers : 3
batch_size : 64

num_samples : 100000
tests :
      - tests/grounded-tests/concap/occ_gender.jsonl
      - tests/grounded-tests/concap/sent-occ_gender.jsonl
      - tests/grounded-tests/concap/weat6.jsonl
      - tests/grounded-tests/concap/sent-weat6.jsonl
      #- tests/grounded-tests/concap/weat8.jsonl
      #- tests/grounded-tests/concap/sent-weat8.jsonl