log_dir : logs
num_gpus : 4
num_workers : 4
val_workers : 2

fpath_stopwords : scripts/stopwords.txt

model_type : visualbert
model_path : visualbert/pretrained-models/nlvr2_coco_pre_trained.th
model_config : visualbert/configs/nlvr2/bias-configs/coco-pre-train-bias.json

tests : [
      tests/tests-images/coco/occ_MF.jsonl,
      tests/tests-images/coco/sent-occ_MF.jsonl,
      tests/tests-images/coco/weat6.jsonl,
      tests/tests-images/coco/sent-weat6.jsonl,
      tests/tests-images/coco/weat8.jsonl,
      tests/tests-images/coco/sent-weat8.jsonl
   ]
features : [
      visualbert/image-features/coco_bias_image_features.th,
      visualbert/image-features/coco_bias_image_features.th,
      visualbert/image-features/coco_bias_image_features.th,
      visualbert/image-features/coco_bias_image_features.th,
      visualbert/image-features/coco_bias_image_features.th,
      visualbert/image-features/coco_bias_image_features.th
]

coco_ontology : visualbert/models/cocoontology.json

# model-specific params
batch_size : 256
num_samples: 100000
bert_cache : .pytorch_pretrained_bert # so we stop trying to go to home dir on machine