log_dir : logs
num_workers : 4
val_workers : 2
batch_size : 256
num_samples: 100000
path_to_obj_list : bottom-up-attention/data/genome/1600-400-20/objects_vocab.txt

test2features : tests/test2features.json
model_type : vlbert
model_archive : pretrained-models/vlbert/vlbert_base_prec.model
model_config_path : pretrained-models/vlbert/model_config.yml
tests :
      - tests/grounded-tests/concap/occ_gender.jsonl
      - tests/grounded-tests/concap/sent-occ_gender.jsonl
      - tests/grounded-tests/concap/weat6.jsonl
      - tests/grounded-tests/concap/sent-weat6.jsonl